---
# tasks file for ansible-role-apt-source
- name: Fail if we're not on Ubuntu
  ansible.builtin.fail:
    msg: "This role only works on Ubuntu"
  when: ansible_facts['distribution'] != 'Ubuntu'

- name: Deploy DEB822 apt sources to /etc/apt/sources.list.d/ubuntu.sources (Ubuntu >= 22.04)
  ansible.builtin.template:
    src: ubuntu.sources.j2
    dest: /etc/apt/sources.list.d/ubuntu.sources
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: ansible_facts['distribution_release'] in ['jammy', 'noble']
  notify: Update apt cache

- name: Empty /etc/apt/sources.list to avoid duplicate sources (Ubuntu >= 22.04)
  ansible.builtin.copy:
    content: "# This file is managed by Ansible. Sources are defined in /etc/apt/sources.list.d/ubuntu.sources\n"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: ansible_facts['distribution_release'] in ['jammy', 'noble']

- name: Deploy apt sources to /etc/apt/sources.list (Ubuntu < 22.04)
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: ansible_facts['distribution_release'] not in ['jammy', 'noble']
  notify: Update apt cache
